apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: minecraft
    namespace: argocd
spec:
    destination:
        namespace: minecraft
        server: https://kubernetes.default.svc
    project: default
    source:
        path: minecraft
        targetRevision: HEAD
        helm:
           valueFiles:
               - values.yaml
                 # - values-lab.yaml
        repoURL: https://github.com/cjohnston1158/deployments.git
    syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
